CREATE TABLE IF NOT EXISTS mentalhealth_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  username VARCHAR(64) NOT NULL COMMENT '用户名',
  password_hash VARCHAR(100) NOT NULL COMMENT '密码哈希（BCrypt）',
  role VARCHAR(32) NOT NULL DEFAULT 'USER' COMMENT '角色（STUDENT/CONSULTANT/ADMIN）',
  nickname VARCHAR(64) DEFAULT NULL COMMENT '昵称',
  avatar_url VARCHAR(256) DEFAULT NULL COMMENT '头像URL',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否1是',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS student_profile (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  real_name VARCHAR(64) DEFAULT NULL COMMENT '真实姓名',
  student_no VARCHAR(64) DEFAULT NULL COMMENT '学号',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否1是',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生档案表';

CREATE TABLE IF NOT EXISTS counselor_profile (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  real_name VARCHAR(64) NOT NULL COMMENT '真实姓名',
  title VARCHAR(64) NOT NULL COMMENT '职称',
  expertise VARCHAR(256) NOT NULL COMMENT '擅长领域',
  intro TEXT DEFAULT NULL COMMENT '个人简介',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否1是',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_id (user_id),
  KEY idx_real_name (real_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询师档案表';

CREATE TABLE IF NOT EXISTS schedule_slot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  counselor_user_id BIGINT UNSIGNED NOT NULL COMMENT '咨询师用户ID',
  date DATE NOT NULL COMMENT '日期',
  start_time TIME NOT NULL COMMENT '开始时间',
  end_time TIME NOT NULL COMMENT '结束时间',
  status VARCHAR(32) NOT NULL COMMENT '状态（AVAILABLE/OCCUPIED/UNAVAILABLE）',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否1是',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_counselor_date (counselor_user_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='排班时段表';

CREATE TABLE IF NOT EXISTS consult_appointment (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id BIGINT UNSIGNED NOT NULL COMMENT '学生用户ID',
  counselor_user_id BIGINT UNSIGNED NOT NULL COMMENT '咨询师用户ID',
  slot_id BIGINT UNSIGNED DEFAULT NULL COMMENT '排班槽位ID（MVP暂可选）',
  start_time DATETIME(3) NOT NULL COMMENT '开始时间',
  duration_minutes INT NOT NULL COMMENT '时长（分钟）',
  status TINYINT NOT NULL COMMENT '状态：1CREATED 2CANCELED 3CONFIRMED 4COMPLETED',
  note VARCHAR(512) DEFAULT NULL COMMENT '备注',
  idempotency_key VARCHAR(64) DEFAULT NULL COMMENT '幂等键',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否1是',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_idempotency (user_id, idempotency_key),
  KEY idx_user_create_time (user_id, create_time),
  KEY idx_counselor_start_time (counselor_user_id, start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询预约表';

CREATE TABLE IF NOT EXISTS consult_thread (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  student_user_id BIGINT UNSIGNED NOT NULL COMMENT '学生用户ID',
  counselor_user_id BIGINT UNSIGNED NOT NULL COMMENT '咨询师用户ID',
  status VARCHAR(32) NOT NULL COMMENT '状态（UNPROCESSED/PROCESSING/CLOSED）',
  topic VARCHAR(256) DEFAULT NULL COMMENT '咨询主题',
  hidden TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否隐藏',
  hidden_reason VARCHAR(256) DEFAULT NULL COMMENT '隐藏原因',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_student (student_user_id),
  KEY idx_counselor (counselor_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询会话线程表';

CREATE TABLE IF NOT EXISTS consult_message (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  thread_id BIGINT UNSIGNED NOT NULL COMMENT '线程ID',
  sender_role VARCHAR(32) NOT NULL COMMENT '发送者角色',
  content TEXT NOT NULL COMMENT '消息内容',
  hidden TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否隐藏',
  hidden_reason VARCHAR(256) DEFAULT NULL COMMENT '隐藏原因',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_thread_create (thread_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询消息表';
